### ISSUE TITLE
Warnings about "Unexpected fixed value"

### ISSUE THREAD

**Issue by bogdanni** [mbtaylor/jcdf#3]
I get multiple warnings while trying to list the content of the attached file (had to gzip it for GitHub):
```
WARNING: Unexpected fixed value 2 != -1
WARNING: Unexpected fixed value 1 != 0
...
```
[solo_L2_mag-rtn-normal-1-minute_20201107_V02.cdf.gz](https://github.com/mbtaylor/jcdf/files/7619432/solo_L2_mag-rtn-normal-1-minute_20201107_V02.cdf.gz)

**Comment by mbtaylor** [comment]
Interesting.  This is complaining about some record fields that were reserved for future use at CDF v3.4 (and updates to v3.6?), which is the version I was coding against when I did most of the implementation, but have become used in more recent CDF versions.  For instance the `Identifier` field in the CDF Descriptor Record (v3.8) was at v3.4 labeled `rfuD`, with the note _"Reserved for future use. Always set to negative 1 (-1)"_ .  Similarly `NumStrings` (née `rfuA`) in the Attribute Entry Descriptor Record.  The existing implementation writes a warning message through the logging system when the constraints it is expecting to see are violated.

I have (evidently) not done a careful check of changes in up to date versions of the CDF Internal Format Description document, so I don't know what other gotchas might have been introduced since I wrote the code.  But to address this one, and similar things (changes of use of "Reserved for future use" fields) that may crop up in the future, I should probably just eliminate those warnings.  I'll try to do that shortly.

**Comment by mbtaylor** [comment]
Should be fixed by a358f63.

**Comment by bogdanni** [comment]
Thanks!
There is also an issue with the EpochFormatter:
```
Exception in thread "main" java.lang.RuntimeException: CDF TIME_TT2000 date formatting failed - library leap second table known to be out of date with respect to data. Update CDF_LEAPSECONDSTABLE environment variable to point at file https://cdf.gsfc.nasa.gov/html/CDFLeapSeconds.txt
	at uk.ac.bristol.star.cdf.EpochFormatter.formatTimeTt2000(EpochFormatter.java:175)
	at uk.ac.bristol.star.cdf.DataType$Tt2kDataType.formatArrayValue(DataType.java:487)
	at uk.ac.bristol.star.cdf.util.CdfList.formatValues(CdfList.java:138)
	at uk.ac.bristol.star.cdf.util.CdfList.run(CdfList.java:112)
	at uk.ac.bristol.star.cdf.util.CdfList.runMain(CdfList.java:225)
	at uk.ac.bristol.star.cdf.util.CdfList.main(CdfList.java:233)
```
The leap seconds list hasn't been updated since beginning of 2017, but the library thinks it should have been.
Shall I open another issue?

**Comment by mbtaylor** [comment]
OK, open a new issue.
